# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptcion',
            new_name='descripcion',
        ),
    ]
