# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('precio',)},
        ),
    ]
